# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2020 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  Publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 6.9.1
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy docs
        run: bash deploy_docs.sh
        env:
          GH_EMAIL: info@inveniosoftware.org
          GH_NAME: inveniobot
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
